.PHONY: day1 day2 day3 all

day1:
	@echo "AOC 2020 - Day 1"
	@go run day1/day1.go day1/util.go

day2:
	@echo "AOC 2020 - Day 2"
	@npx ts-node day2/day2.ts

day3:
	@echo "AOC 2020 - Day 3"
	@ruby day3/day3.rb

all: day1 day2 day3
