.PHONY: day1 day2 day3 day4 all

day1:
	@echo "AOC 2020 - Day 1"
	@go run day1/day1.go day1/util.go

day2:
	@echo "AOC 2020 - Day 2"
	@npx ts-node day2/day2.ts

day3:
	@echo "AOC 2020 - Day 3"
	@ruby day3/day3.rb

day4:
	@echo "AOC 2020 - Day 4"
	@cd day4 && cargo run src/data

all: day1 day2 day3 day4
